### ISSUE TITLE
channel deleter/role deleter isn't working

### ISSUE THREAD

**Issue by Drifty96** [Gowixx/okuru-nuker#11]
![image](https://user-images.githubusercontent.com/84033013/117847533-b6f60080-b282-11eb-8b9c-0d85f0c0cff6.png)

**Comment by Drifty96** [comment]
this is all it does, then it goes back to menu.

**Comment by zCircleBallX** [comment]
Hello there, Drfty96!
The channel deletion does work!
All you need to do is scrape then restart the program.
If you do that, you can channel delete.
I know it’s a pain, but oh well!

**Comment by Drifty96** [comment]
Oh ty

**Comment by zCircleBallX** [comment]
That’s why it says,
![78A7CDE7-070A-4957-A0FA-81B8F0F0113F](https://user-images.githubusercontent.com/84060010/118002506-85ba1680-b2fc-11eb-812d-b74670d2e0b5.jpeg)

**Comment by Gowixx** [comment]
Thanks for the help Krypton
